name: "CI: Check Code Formatting"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Code Formatting
      run: |
        # Prevent blocking the install on a question during configuring of tzdata.
        export ENV DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt install build-essential mm-common clang-format-10 --yes
        sudo ln -sf /usr/bin/clang-format-10 /usr/bin/clang-format
        ./autogen.sh --enable-warnings=fatal
        make check-format
