name: "CI: cmake: msvc 2019"

# This test does not work any more. Don't run it automatically.
# I don't know how it shall be changed. /2020-11-25 Kjell Ahlstedt
on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build
      run: |
        cmake .
        msbuild ALL_BUILD.vcxproj
    - name: Test
      run: msbuild RUN_TESTS.vcxproj
